version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_eventos
    restart: always
    environment:
      POSTGRES_DB: eventos
      POSTGRES_USER: caio
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
